name: "actions-template-sync"
description: "Synchronises changes of the template repository"
author: "AndreasAugustin"
branding:
  icon: cloud
  color: green
inputs:
  github_token_remote:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  github_token_local:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  source_repo_path:
    description: "Repository path of the template"
    required: true
  upstream_branch:
    description: "The target branch"
  source_repo_ssh_private_key:
    description: "[optional] private ssh key for the source repository. E.q. useful if using a private template repository."
  pr_branch_name_prefix:
    description: "[optional] the prefix of branches created by this action"
    default: "chore/template_sync"
  pr_title:
    description: "[optional] the title of PRs opened by this action"
    default: "upstream merge template repository"
  pr_labels:
    description: "[optional] comma separated list of pull request labels"
  pr_reviewers:
    description: "[optional] comma separated list of pull request reviewers"
  pr_commit_msg:
    description: "[optional] the commit message of the template merge"
    default: "chore(template): merge template changes :up:"
  hostname:
    description: "[optional] the hostname of the GitHub repository"
    default: "github.com"
  is_dry_run:
    description: "[optional] set to true if you do not want to push the changes and not want to create a PR"
  is_allow_hooks:
    description: "[optional] set to true if you want to allow hooks. Use this functionality with caution!"
    default: "false"
  is_not_source_github:
    description: "[optional] set to true if the source repository is not a github related repository. Useful e.q. if the source is GitLab"
    default: "false"
  git_user_name:
    description: "[optional] set the committer git user.name for the merge commit"
  git_user_email:
    description: "[optional] set the committer git user.email for the merge commit"
  git_remote_pull_params:
    description: "[optional] set the pull parameters for the remote repository"
runs:
  using: "docker"
  image: "src/Dockerfile"
  env:
    GITHUB_TOKEN_REMOTE: ${{ inputs.github_token_remote }}
    GITHUB_TOKEN_LOCAL: ${{ inputs.github_token_local }}
    SOURCE_REPO_PATH: ${{ inputs.source_repo_path }}
    UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
    SSH_PRIVATE_KEY_SRC: ${{ inputs.source_repo_ssh_private_key }}
    PR_BRANCH_NAME_PREFIX: ${{ inputs.pr_branch_name_prefix }}
    PR_TITLE: ${{ inputs.pr_title }}
    PR_LABELS: ${{ inputs.pr_labels }}
    PR_REVIEWERS: ${{ inputs.pr_reviewers }}
    PR_COMMIT_MSG: ${{ inputs.pr_commit_msg }}
    HOSTNAME: ${{ inputs.hostname }}
    IS_DRY_RUN: ${{ inputs.is_dry_run }}
    IS_ALLOW_HOOKS: ${{ inputs.is_allow_hooks }}
    IS_NOT_SOURCE_GITHUB: ${{ inputs.is_not_source_github }}
    GIT_USER_NAME: ${{ inputs.git_user_name }}
    GIT_USER_EMAIL: ${{ inputs.git_user_email }}
    GIT_REMOTE_PULL_PARAMS: ${{ inputs.git_remote_pull_params }}
